### PR TITLE
Add Jest support.  Removes setup and spy retrieval.

### PR DESCRIPTION
**Pull request by ike18t**
This is a bit opinionated but removing setup simplifies the API and the underlying code.  Removing it makes it easier to steer the users in a direction (rather than having two ways to accomplish the same thing?) while also making this lib easier to maintain.

### CODE REVIEW

**Comment by ike18t** [comment]
Shout out to Barry Wilks for bringing jest support to my attention as well as helping me verify compatibility.

**Comment by jjherscheid** [comment]
I cannot get it to work. Keep getting errors when running with jasmine. Jest seems to work.

I think you are right about keeping the interface simple, so we should remove the setup() part but I a lot of projects setup is still used.

The thing I was wondering about isn't it better to publish this libary with a different name (ts-mocking, don't really know another good name). But this way you could publish it yourself. Currently I am not working with typescript and I feel like holding you up with releasing just because I have to check the Pull Requests ;-).

Don't get met wrong I really like the fact that you spend so many time with this project. But this way you can publish the library youself without having to create pull requests all the time. And I can update the original ts-mocks when I want (because we use it in a lot of projects with the setup part ;-))

What do you thinks about this. I don't really know a good name (ts-mocking ?)

**Comment by ike18t** [comment]
Those errors are because of typing definition files for jasmine and jest conflicting.  If you change an assertion to make it fail, it will actually cause a legit failure so the tests are passing with jasmine.

I understand and I'm cool with starting a new lib.  I've thought about it before but I didn't want to step on your toes.  I'm thinking ts-mockery...but that may change.  :-P

**Comment by jjherscheid** [comment]
Ah.. so now I understand. About the errors ;-).

No.. you are not stepping on my toes :D. I really learned a lot of all the PR's you've made. But I think for you it's also more convenient to not have to create PR all the time ;-).. 
Once you created your own libary let me know. Then I will abandon this PR. But also will add the link to your lib on my readme. So that people who want to have the plugin structure can use your library. 

ts-mockery sounds nice ;-)...

**Pull request closed without merging**
