### PR TITLE
Add ability to partially implement in constructor

### PR DESCRIPTION
**Pull request by ike18t**
Also added tests, upgraded deps, and added a method to quickly extend a mock.

### CODE REVIEW

**Comment by jjherscheid** [comment]
Great work!
I will try to merge the PR this week and update the ts-mock version in npm.
Tanx

**Comment by ike18t** [comment]
Thanks man!  I have a one more commit that I'm going to add to this as well.  You instantiate a mock with an object that already has a spy on a method there will be a blow up.  There really isn't an elegant way, that I'm aware of, to verify if a spy is already on a function so I'm just going to wrap it in a try..catch.   ¯\_(ツ)_/¯

**Comment by jjherscheid** [comment]
Great, I will wait for the commit. I am currently not working on a typescript project so I appreciate the work you've done, to make this library better :-)

**Comment by ike18t** [comment]
It has been comitted:
https://github.com/jjherscheid/ts-mocks/pull/4/commits/3fe3ee5d8e7c8e6d980a3dbfbf7b193b8bbb417a

**Comment by ike18t** [comment]
No problem!  I've been engulfed in TS and angular and we have found this library to be super helpful.  Type-safety FTW!

**Comment by ike18t** [comment]
One more thought.  With this PR the need for the setup method kind of goes away.  Your call but we could give deprecation warnings for that method.

**Comment by jjherscheid** [comment]
I will look into that ;-).  Tnx..
I even want to set the version to 1.0.0
Thanks to you it finally has unit tests :-D

**Comment by jjherscheid** [comment]
Just merged the pull request. I've change some things and added more tests... I also created npm version 1.0.0.. Can you review if it is still working properly. I could not find any problems.

Tnx

**Comment by ike18t** [comment]
It all looked good to me.  Sorry about the missing ";".  I'm used to a combination of tslint and this vim https://github.com/Quramy/tsuquyomi keeping me in check.

I did notice one minor issue.  I just submitted a 2nd PR.  If you don't specify the generic type to Mock and pass in an object that has private members then you will get a compile error.

**Pull request merged**
